import Image from "next/image";
import Logo from "/public/logo-w.svg";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
      <footer className="p-8 flex justify-around bg-nua-purple-secondary text-nua-white-main font-text font-bold">
        <span>
          <p>Vive Nua, vive felicidad </p> <p> Nua © 2023 </p>
        </span>
        <span>
          <a
            href="https://www.vivenua.com"
            target="_blank"
            rel="noopener noreferrer"
          >
            <Image className="m-auto" src={Logo} alt="logo" height={25} />
            <p className="text-sm">Conoce Vive Nua</p>
          </a>
        </span>
        <span>
          <p>Siguenos</p>
          <div>
            <a
              href="https://www.facebook.com/profile.php?id=100090857894017"
              target="_blank"
              rel="noopener noreferrer"
            >
              f
            </a>
            <a
              href="https://www.instagram.com/vivenua/"
              target="_blank"
              rel="noopener noreferrer"
            >
              [oº]
            </a>
            <a
              href="https://www.linkedin.com/company/vivenua/jobs/"
              target="_blank"
              rel="noopener noreferrer"
            >
              in
            </a>
          </div>
        </span>
      </footer>
    </html>
  );
}
