import Image from "next/image";
import Logo from "/public/logo-w.svg";
import "./globals.css";
import { Inter } from "next/font/google";
import LinkedInIcon from "/public/linkedin.svg";
import InstagramIcon from "/public/instagram.svg";
import FacebookIcon from "/public/facebook.svg";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const ICON_SIZE = 40;

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <footer className="h-32 text-md sm:text-xs grid grid-cols-7 items-center bg-nua-purple-secondary text-nua-white-main font-text font-bold">
          <span className="col-start-2">
            <p>Vive Nua, vive felicidad </p> <p> Nua © 2023 </p>
          </span>
          <span className="col-start-4 text-center">
            <a
              href="https://www.vivenua.com"
              target="_blank"
              rel="noopener noreferrer"
            >
              <Image className="m-auto" src={Logo} alt="logo" height={25} />
              <p className="text-sm">Conoce Vive Nua</p>
            </a>
          </span>
          <span className="col-start-6">
            <p className="font-title font-bold text-xl pb-2">Siguenos</p>
            <div>
              <a
                href="https://www.facebook.com/profile.php?id=100090857894017"
                target="_blank"
                rel="noopener noreferrer"
              >
                <Image
                  className="inline"
                  src={FacebookIcon}
                  alt="facebook"
                  height={ICON_SIZE}
                />
              </a>
              <a
                href="https://www.instagram.com/vivenua/"
                target="_blank"
                rel="noopener noreferrer"
              >
                <Image
                  className="inline mx-2"
                  src={InstagramIcon}
                  alt="instagram"
                  height={ICON_SIZE}
                />
              </a>
              <a
                href="https://www.linkedin.com/company/vivenua/jobs/"
                target="_blank"
                rel="noopener noreferrer"
              >
                <Image
                  className="inline"
                  src={LinkedInIcon}
                  alt="linkedin"
                  height={ICON_SIZE}
                />
              </a>
            </div>
          </span>
        </footer>
      </body>
    </html>
  );
}
